### ISSUE TITLE
Proper testing of all matching hotkeys

### ISSUE THREAD

**Issue by ChrisS85** [Lexikos/AutoHotkey_L#15]
I believe I have mentioned this issue before on the forums, but I consider it a huge lack of the current hotkey handling which is an important point of the language. It's something where AHK is lacking flexibility where it shouldn't have to IMO.

Consider this example:

	Hotkey, If, Condition()
	Hotkey, ~^v, label
	Hotkey, ^v, label
	return

	#if Condition()
	label:
	Tooltip not captured
	return

	Condition()
	{
		tooltip % A_ThisHotkey
		return A_ThisHotkey = "~^v"
	}

It is meant to execute the code with a non-capturing hotkey. However, only the first (^v) hotkey is tested, the condition returns false and the registered ~^v hotkey isn't even checked. If the direction of registration is inverted it works properly. Something like this is forbidden with a "Duplicate hotkey" message:

	#if Condition()
	^v::
	Tooltip captured
	return

	#if Condition()
	~^v::
	Tooltip not captured
	return

I believe that both should be possible, since the Condition() function may depend on A_ThisHotkey and return dfiferent results. In one situation one might want to capture a hotkey while in another it is undesirable. I think that AutoHotkey should execute each label where the hotkey and condition matches. In the first example this should result in the label being called two times.

Are there technical reasons that speak against this? If so, how to properly circumvent the issue of the first example, when the hotkeys may be defined dynamically by the user?
I would've attempted to implement it myself, but I'm afraid I won't get it to work properly.

**Comment by Lexikos** [comment]
Several years later...

I still don't think the idea has much use or that it would even work logically.

> I believe the best solution that shouldn't require any signifcant effort would be to treat the ~ modifier like the * modifier (that is, don't consider them as equal in the assignment of a label to a Hotkey).

As of v1.1.15 (May 2014) the Hotkey command is capable of adding or removing the ~ modifier of a hotkey variant, so this is definitely not going to happen.

> That implementation also allows to write AHK code that allows multiple handlers for a hotkey through a generic handler function where each hotkey is registered.

So does the current implementation.  Actually, since v1.1.20 (March 2015) it is even easier, as instead of a label, you can have the hotkey call a function with parameters given when the hotkey was registered (such as an array of functions which can be continually updated).

If anyone thinks the idea has merit, they can prove it by implementing it in script.
