### ISSUE TITLE
A_CaretX and A_CaretY does not work properly on browsers

### ISSUE THREAD

**Issue by danielo515** [Lexikos/AutoHotkey_L#35]
The title says it all: A_CaretX and A_CaretY returns invalid values when editing text in browsers. I tested it on windows 7, chorme and firefox.

Is this a know bug?

**Comment by Lexikos** [comment]
It's a documented limitation.

>  Note that some windows (e.g. certain versions of MS Word) report the same caret position regardless of its actual position.

Basically, Chrome and other browser don't use the system caret, just like they don't use standard Windows controls.

**Comment by Lexikos** [comment]
I presume the "invalid" values you were getting were the top-left of the window's client area.  This is because GetCaretPos returns 0,0, which AutoHotkey then converts to screen or window coordinates.  Since GetCaretPos returns "success", AutoHotkey must assume that there is a caret and the coordinates are valid.

However, I've done some testing and found that GetGUIThreadInfo reliably shows when there really is no caret.  Therefore, commit d934ffa changes A_CaretX and A_CaretY to use GetGUIThreadInfo instead of AttachThreadInput and GetCaretPos.  As a bonus, the variables now work with console windows.
