### ISSUE TITLE
hold key issue

### ISSUE THREAD

**Issue by dutrieux** [Lexikos/AutoHotkey_L#46]
Hello,

I juste would like to repeat 'x' when a key is hold but I have a strange issue :

```javascript

$&::
	While GetKeyState("&","p") { ; While it is held down
		Send X
		Sleep 100
	}
return

```

Every time I down the key, the 'X' is repeat but sometime '1' is insert :

Juste see my video for I best explanation : [YouTube](https://youtu.be/24coSMqcesA?vq=hd1080)

I remark that if I send x (in lowercase) I don't have this problem.

note : I use windows 10 x64 and try with v1.1.22.07 & v1.1.12.00 of ahk with the same effect

Duto

**Comment by Gitoffthelawn** [comment]
@dutrieux Sorry for the OT, but what screen recorder did you use for that example?  It's very smooth.

**Comment by dutrieux** [comment]
@Gitoffthelawn I use shadowPlay by Nvidia

**Comment by dutrieux** [comment]
I remark that if I send x (in lowercase) I don't have this problem.

**Comment by Gitoffthelawn** [comment]
@dutrieux Thanks.  That explains why it looks so good.  Impressive.

**Comment by Lexikos** [comment]
I'm usually not interested to investigate these sort of reports, because sending keystrokes is inherently unreliable - this is why there are several ways of sending keystrokes, and settings for delays. In this case, you are physically using the keyboard while the script is also manipulating the keyboard state. It is not likely to be a bug.

I have watched your video, and in the key history, it looks like `1` and `&` are the same key for you. I assume that you type `1` by holding Shift and pressing `&`. Therefore, `1` appears when the `&` key repeats while the Shift key happens to be in the "pressed" state for sending X.

I was easily able to reproduce the problem using your script but replacing `&` with `1`, which is unshifted on the US layout; and also the following:

    $1::  ; Replace this with any unshifted key.
    SetKeyDelay 100, 100
    Send X
    return

The same problem would occur when sending an unshifted character from a shifted hotkey.

I was not able to reproduce the problem with **SendInput** or **SetKeyDelay -1, -1** (and your loop).
