### ISSUE TITLE
Unicode Key only up to {U+FFFF}?

### ISSUE THREAD

**Issue by ewerybody** [Lexikos/AutoHotkey_L#62]
Unicode is surely a topic on it's own :/
So you know the 👍 is [U+1F44D](http://unicode-table.com/en/1F44D/). That's 5 digits!
The [Autohotkey Send docs](https://autohotkey.com/docs/commands/Send.htm#Unicode) say {U+nnnn} and if you want to do something like:

`Send, {U+1F44D}` it actually omits the 1 and gives you .

Is this known? Is it a bug? How would I do it correctly.

I hope I'm right here :] Didn't have access to the forum right away. But I'm just on github. soo.

**Comment by hi5** [comment]
You can just do `Send 👍`  if you use the AutoHotkey Unicode version and save your script in the correct format.

**Comment by Lexikos** [comment]
I don't consider it a bug.  `{U+nnnn}` implies that only 4 digits are supported.

> If the character doesn't map to a virtual keycode, SendInput() or WM_CHAR is used to send the character 

For SendInput(), a [KEYBDINPUT](https://msdn.microsoft.com/en-us/library/ms646271) struct is prepared for each keystroke or character.  Character codes are placed in the `wScan` field, which is 16-bit.  That means only values in the range 0 to 0xFFFF are accepted.

For WM_CHAR, the official documentation claims that it uses UTF-16, but the only mention of supplementary characters is that WM_UNICHAR supports them.  I was unable to get WM_UNICHAR to have any effect whatsoever.  You have to read between the lines to understand that **two** WM_CHAR messages are sent for each surrogate pair.  When you do `ControlSend,, 👍, A`, AutoHotkey posts two WM_CHAR messages (simply because ControlSend treats surrogate pairs as two characters), and this works in Edit and RichEdit controls, Internet Explorer, Chrome and others.

But because it's not clear in the documentation, it's less likely for anyone implementing a WM_CHAR handler to actually get it right.  For instance, the Scintilla control was fixed only this year (3.6.3) to support "non-BMP input through WM_CHAR".  Notepad++ (7.2) still uses an older version, so it doesn't support it.

It turns out that SendInput() works the same way, most likely because it doesn't really understand supplementary characters but ends up producing two WM_CHAR messages.

Now that I know this, I might enhance {U+nnnn} to work as expected (although this feature is obsolete as hi5 pointed out).

**Comment by ewerybody** [comment]
Cannot repro :/

So "save your script in the correct format": **UTF-8** is enough, right? When I save 👍 like that and open it back up: It's `ðŸ‘` but setting **Encoding** > **Encode in UTF-8** makes it 👍 again.
Doing this with **Encoding** > **Convert to UTF-8-BOM** then it's always 👍.

To be super clear: This is what I do:
- I create a new file with with Notepad++ (ANSI is default)
- set **Encoding** > **Convert to UTF-8-BOM**
- I add a line `#z::Send, 👍`
- I add a line `^#z::ControlSend,, 👍, A,`
- I add a line `:*:ccc::👍`
- I save it and run it with latest Autohotkey 64 Unicode (got nothing else installed)

This brings me to the first success message:
- the HotString works here in the browser 👍, works in Explorer, works in Eclipse ... nice!

Everything else doesn't seem to do the right thing:
- triggering the Hotstring in Notepad++ with any UTF-8 encoding gives me `🐀𣐀` (yea the [rat](http://unicode-table.com/en/1F400/)! 1F400. missing the 4D... hmm might be Notepads fault? But one can paste the thumb in general)
- the Send-Hotkey does nothing at all here in the Browser. It works in Eclipse tho 👍 and in Explorer 👍 (With all the different Send[X] methods)
- the ControlSend-Hotkey never does anything at all
- setting it only to UTF-8 without BOM gives me `ðŸ‘` 

So yea: I had to make my chain of includes all to UTF-8-BOM (or encoding='utf-8-sig' in Python). But still: seems there are some issues.

**Comment by Lexikos** [comment]
> triggering the Hotstring in Notepad++ with any UTF-8 encoding gives me 🐀𣐀

I already explained that. Search for "Notepad++" in my previous comment.

For me, the ControlSend hotkey has the same effect as the others.

**Comment by ewerybody** [comment]
👍 Yep. But it's still weird for me as an Autohotkey user that stuff comes out so differently
I mean I can actually bypass with context sensitive Hotkeys to just paste such a character in Firefox and Notepad++

Lexikos, do you have an Idea what's causing the ControlSend not to do anything?

Thanks for the input already!
After all: Lots of nice stuff to learn here!! :]

**Comment by Lexikos** [comment]
Commit 364e2e66 (v1.1.24.03) adds support for `{U+x}` where x > 0xFFFF.

**Comment by ewerybody** [comment]
Awesome! :] Thanks a lot! 👍
