### ISSUE TITLE
_Struct fails when used in a class

### ISSUE THREAD

**Issue by lipkau** [Lexikos/AutoHotkey_L#64]
I am writing a code where I want to get the cursor info. In my code, this is called in a method of a class. Such as:
```
#include lib\ahklib\_Struct.ahk

class foo
{
    __New()
    {}

    Exec()
    {
        POINT := "Long x,Long y"
        mi := new _Struct("DWORD cbSize, DWORD flags, HCURSOR hCursor, POINT ptScreenPos")
        mi.cbSize:=sizeof(mi)
        DllCall("GetCursorInfo", "Ptr", mi[])

        MsgBox % "cbSize:`t`t`t"         mi.cbSize        "`n"
               . "flags:`t`t`t"          mi.flags         "`n"
               . "hCursor:`t`t`t"        mi.hCursor       "`n"
               . "x-coordinate:`t`t"     mi.ptScreenPos.x "`n"
               . "y-coordinate:`t`t"     mi.ptScreenPos.y
    }
}

bar := new foo()
bar.Exec()
```

This **fails**. AHK hangs and I must terminate the process.

However, if I run the same code outside of the class, this works:
```
#include lib\ahklib\_Struct.ahk

POINT := "Long x,Long y"
mi := new _Struct("DWORD cbSize, DWORD flags, HCURSOR hCursor, POINT ptScreenPos")
mi.cbSize:=sizeof(mi)
DllCall("GetCursorInfo", "Ptr", mi[])

MsgBox % "cbSize:`t`t`t"         mi.cbSize        "`n"
       . "flags:`t`t`t"          mi.flags         "`n"
       . "hCursor:`t`t`t"        mi.hCursor       "`n"
       . "x-coordinate:`t`t"     mi.ptScreenPos.x "`n"
       . "y-coordinate:`t`t"     mi.ptScreenPos.y
```

Why is that?

_This is also reported in HotKeyIt's repo: https://github.com/HotKeyIt/_Struct/issues/4_

**Comment by Lexikos** [comment]
It doesn't "hang"; it crashes with exception 0xC00000FD (stack overflow), because of infinite recursion within _Struct when it fails to find a definition of POINT.  Scripts can't retrieve **local** variables of other functions.

Please avoid posting here in future unless you can confirm that it is a bug with AutoHotkey.  There are many more people with the ability and inclination to help on the forums than here.
