### ISSUE TITLE
ExitWindowsEx function maybe should not be called with dwReason == 0

### ISSUE THREAD

**Issue by mslattery** [Lexikos/AutoHotkey_L#66]
In Microsoft's documentation for the ExitWindowsEx function 

(see https://msdn.microsoft.com/en-us/library/windows/desktop/aa376868(v=vs.85).aspx)
They indicate, "This parameter must be one of the system shutdown reason codes ... Therefore, do not use zero for this parameter."

AutoHotkey_L calls this with this parameter set to 0, see below

// ExitWindows
	if (ExitWindowsEx(nFlag, 0))
		return true;
	else
return false;

**Comment by Lexikos** [comment]
So?

You omitted the important part: why it says not to use zero.

> If this parameter is zero, the SHTDN_REASON_FLAG_PLANNED reason code will not be set and therefore the default action is an undefined shutdown that is logged as "No title for this reason could be found". By default, it is also an unplanned shutdown.

Seems appropriate enough, since the user didn't (can't) specify the reason.

> Depending on how the system is configured, an unplanned shutdown triggers the creation of a file that contains the system state information, which can delay shutdown. 

I suppose that on a system configured to create this file on unplanned shutdown, this is appropriate. Maybe it *is* an unplanned shutdown.

I'd be interested to know whether AutoIt's Shutdown function has the same effect (but not interested enough to test it myself), since it seems AutoHotkey's Shutdown command is [based on early AutoIt v3 source code](https://autohotkey.com/board/topic/2916-three-thumbs-up/#entry18972).  AutoIt doesn't allow a reason code to be specified either.

**Comment by mslattery** [comment]
I'm just pointing out what Microsoft has indicated as an issue for us.

I selected the title as "...maybe should not be called with dwReason == 0", so that was meant to indicate that there may not be a good reason, but I wonder if it makes sense, in this case, to consider making the reason a parameter if an end-user wants to specify it.

For example, we capture a keystroke then call shutdown, we of course can set the reason to something other than zero as appropriate.

Just wanted to share my experience with Microsoft on the issue.

Thanks for the attention and the good work. Feel free to close if you see it as a non-issue.
-Mike
