### ISSUE TITLE
Issues with middle click in Logitech MX Mouse and Setpoint

### ISSUE THREAD

**Issue by mundodisco8** [Lexikos/AutoHotkey_L#70]
Hi!
I'm trying to make a script that, when I press the middle button on my mouse (a logitech MX master) behaves as if space + left click is being pushed, until I release the middle button. 

I tried this code
```
MButton::
  Send {Space Down}{LButton Down}
  KeyWait, Mbutton
  Send {Space Up}{Lbutton Up}
return
```

and this somewhat more convoluted version, that will print the status of the key in a debug console. I added mouse hooks because I think it's an alternative way of getting the state, but I really don't understand it. In any case, it doesn't make a difference

```
//Debugging Console
Print(str) {
  static create = true, output
  if create {
    create =
    Gui, 99: -Caption
    Gui, 99:Margin, 0, 0
    Gui, 99:Add, Edit, w500 r5 voutput
    x := A_ScreenWidth - 500
    Gui, 99:Show, NoActivate x%x% y0
  } else
    GuiControlGet, output, 99:
  GuiControl, 99: , output, %output%%str%
  Gui, 99:Show, NoActivate
}

MButton::
#UseHook, on
Loop
{
    Sleep 500
    GetKeyState, state, MButton, P
    if not GetKeyState("MButton", "P")
        break
    print(state)
}
print(state)
#UseHook off
return
```

This code will print U straight away, the mouse button shows as UP, even if I'm pressing it.

The reason I think it's a bug (not necessarily yours, but that you might be able to correct) is that this code works with the left and right mouse. There is something preventing it to work with the middle button.

I've searched a bit and seen people with similar problems to mine (although it's from 2009)
https://autohotkey.com/board/topic/43681-keywait-on-middle-mouse-button-logitech-setpoint/

I'm using windows 10, logitech setpoint 6.20.43 and autohotkey 1.1.24.02. Any ideas?

Thanks!

**Comment by hi5** [comment]
Post on the forum for help, not here.

**Comment by mundodisco8** [comment]
I'm not looking for help, I'm reporting that on my mouse, keywait or getkeystate work on 4 out of 5 mouse keys, and providing an instance of at least another user with the same issue. If you need me to fill a report, please point me to your guidelines for reporting, or if this is a known error or you think that this is not something for autohotkey to fix, then fine.

**Comment by hi5** [comment]
I mean that a better way to get feedback on your problem - either a fix or confirmation of an actual bug (your report seems to be hardware specific) would be to post on the autohotkey.com forum - you don't even have to register, you can post in Ask for Help as a guest - more people are likely to see it there, perhaps with the same hardware as you have. They may have a solution.

In general when you use multiple programs that can control a keyboard, clipboard our mouse, don't be surprised things don't work together that well as they might fight for control over the keyboard, clipboard or mouse - what happens if you disable / remove setpoint software for example?

Just my 2cts.

**Comment by mundodisco8** [comment]
You're right. I'll ask in the forum and see if it has an easy fix.
Thanks for your help, if i sounded ungrateful on my last email it was not my intention

**Comment by Lexikos** [comment]
If your problem is the same as in the topic you linked to, this is not a bug in AutoHotkey nor a bug in any other software.

There's an explanation in the topic you linked to:

> the MButton keyup event appears as "**Artificial**"

> with setpoint disabled everything works like a charm (because the middle up event is no longer "artificial"

... and in the manual:

> [KeyWait] If this parameter is blank, the command will wait indefinitely for the specified key or mouse/joystick button to be **physically** released by the user.

> [GetKeyState] P: Retrieve the **physical** state (i.e. whether the user is physically holding it down). 

Emphasis added.

For the OP of that topic at least, the standard middle mouse button is not being *physically* pressed as far as the OS or any software is concerned.

Retrieving the logical (L) state with GetKeyState would not work either, since the button is never logically pressed: you are blocking it with a hotkey.

If you want to detect artificial MButton-up, use a hotkey.

    MButton up::
